# Site settings
title: Grimoire
email: me@arrdem.com
description: "Community documentation of Clojure"
url: "http://grimoire.arrdem.com"
baseurl: /
version: "0.2.6"
clojure_version: "1.6.0"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty

JB:
  analytics:
    provider: google
    google:
      tracking_id: "UA-44001831-2"

author:
  me:      "http://arrdem.com/"
  github:  "https://github.com/arrdem/grimoire"
